### PR TITLE
Build & Deploy Packagingtest Docker images

### PR DESCRIPTION
**Pull request by armab**
Work on https://github.com/StackStorm/st2-dockerfiles/issues/40 to build & deploy `packagingtest` Docker images automatically to quay.io.

### CODE REVIEW

**Comment by armab** [comment]
@enykeev I started suspecting that official docker Hub is the way to go again.

See automated build configured for `packagingtest`: https://hub.docker.com/r/arma/test/builds/
Works on every push to `master`.

And no BS with tags like in Quay.io, since `Dockerfile` is associated with hardcoded `tag`.
Also it's possible to configure it to build the images correctly on any tag creation aka "GitHub Release" instead of Push.



----

IMO we can use Quay.io only if build + upload Docker images from CI, instead of via built-in Quay.io machinery. At least I don't see how to do it right with those tags.
Deleting + Adding tag every time for repo to trigger Dockerfiles build is very counter-intuitive.

^^ 
@enykeev any opinions?

**Comment by armab** [comment]
@enykeev Another approach if we want `Quay` so much, is just to create new repository for each image and don't use named tags.
As a bonus, we could start tagging our build/test Docker images with normal version tags (`v0.0.1`).

So re-building Images will be easy as creating new GitHub release (`v0.0.2`).

Additionally, if sticking with Quay the good idea will be anbling Vulnerability notifications.



So the workflow will be:
- If there is new Slack notification from Quay -> Go to https://github.com/StackStorm/st2-dockerfiles/releases and create new `v0.0.X` Release.
- If something is wrong with update, - it's possible to temporary pin previous version in `st2-packages` `docker-compose.yml`

**Comment by armab** [comment]
So putting everything together, both solutions will work.

- Docker Hub: 
  - 2 repos as before
  - 4 tags per each repo as it was before
    - `packagingrunner:centos6`
    - `packagingrunner:centos7`
    - `packagingrunner:trusty`
    - `packagingrunner:xenial`
    - `packagingtest:centos6-sshd`
    - `packagingtest:centos7-systemd`
    - `packagingtest:trusty-upstart`
    - `packagingtest:xenial-systemd`
  - automated builds (on every git push)
  - easy to configure
  - cons: 1 parallel build (not a big deal)
- Quay.io:
  - 8 repos, create repository for every image
    - `packagingrunner-centos6`
    - `packagingrunner-centos7`
    - `packagingrunner-trusty`
    - `packagingrunner-xenial`
    - `packagingtest-centos6-sshd`
    - `packagingtest-centos7-systemd`
    - `packagingtest-trusty-upstart`
    - `packagingtest-xenial-systemd`
  - automated builds
  - bonus: version docker images via `v0.X.X` tag
  - security notifications in Slack from Quay

Let me know which one you like better and why.

**Comment by enykeev** [comment]
I want to remind you that the reason we switched back to Quay was the connectivity problems between CircleCI and Docker Hub resulting in builds failing, sometimes several times in a row. Switching back to Hub is not an option unless we're sure it's been fixed.

I personally see no problem in deleting and recreating tags for Quay given that we have some form of automation for that. We can use CircleCI for that or we can use StackStorm (dogfooding).

We can go as far as to use both quay and hub and have a backup for the time when things started to go sour with one of them. It will cost us little additional maintenance, but allow us to try and evaluate both and have some much needed resiliency for our package build process (we can fall back to another repo when we unable to pull images from primary one).

The option with 8 repos doesn't strike me fancy though.

**Comment by armab** [comment]
After another try to go with `named` tags in Quay, - I give up.

In short, assigning existing tag to newest commit in git is not picked up by Quay, instead they monitor it only when tag is created. Even doing that will require force-push, it's nasty and counter-intuitive. Definitely not the part of the "smooth Docker building" story by contributors (see https://github.com/StackStorm/st2-dockerfiles/issues/40 why).

I will create repo for each image in Quay, which works perfectly fine (their original story/assumption).

So many repos is still ugly, because it's about chosing between the least ugly hack, but will work more flawlessly and with less guesses:
- push to `master` -> `latest` docker tag
- new `0.0.1` release -> `0.0.1` docker tag

**Comment by armab** [comment]
Also @enykeev BTW currently biggest part of our Docker images are in Docker Hub, not in Quay.

See: https://github.com/StackStorm/st2-packages/blob/master/docker-compose.circle.yml

Maybe it was something temporary in Docker Hub.

**Comment by armab** [comment]
Keeping in mind last argument ^^ that we already using Docker Hub `packagingenv` and `packagingtest` images with no connectivity issues recently, I'll create Docker Hub automated builds first.

Maybe it worth to do the same for Quay later.

**Comment by armab** [comment]
Keeping in mind last argument ^^ that we already using Docker Hub `packagingenv` and `packagingtest` images with no connectivity issues recently, I'll create Docker Hub automated builds first.

Maybe it worth to do the same for Quay later, but Hub at the moment easiest solution.

**Pull request merged**
