### PR TITLE
python3.8 / Ubuntu Focal migration

### LINKED ISSUE #53: Switch from Ubuntu18 (py3.6) -> Ubuntu20 (py3.8)
Currently, StackStorm Docker images rely on Ubuntu 18.04 LTS with py3.6.
https://github.com/StackStorm/st2-dockerfiles/blob/84036d3997ece37088d8831c9b6a53747117849a/base/Dockerfile#L1

Because Python 3.6 is EOL in 2021, we need to switch to Ubuntu 20.04 LTS that's shipped with py3.8 for running StackStorm environment.
https://thenewstack.io/time-to-say-goodbye-python-3-6-is-end-of-life/

### PR DESCRIPTION
**Pull request by jstaph**
A naive PR to migrate to Ubuntu Focal.  I'm calling it naive, as I'm unfamiliar with what I should be doing to validate and verify the changes, but it seems to be working for me.  Happy for feedback, suggestions, etc.

fixes #53

### CODE REVIEW

**Review by armab — APPROVED** [review]
That's nice!

Thanks a lot for covering all the places :+1: 

Could you also prepare the PRs in docker and K8s repos with the changelog update?
https://github.com/stackStorm/st2-docker/
https://github.com/StackStorm/stackstorm-ha/
And so we could merge them during the next st2 release when the focal docker changes will be promoted to stable.

**Comment by jstaph** [comment]
Much appreciated!  I'll get you PR's for the other repos.

Thanks again for the merge, and the compliment!

**Comment by rite2hhh** [comment]
Did this make into StackStorm v3.7?

I don't see the changelog entry (https://github.com/StackStorm/st2-docker/pull/238/files)
for either st2 v3.7 or latest version at https://docs.stackstorm.com/latest/changelog.html.

It's unclear based on the changelog date 2022-05-06 (a day after v3.7 release) vs when the
changes were actually committed (Feb 12)

**Comment by armab** [comment]
@rite2hhh Yes, it's part of the v3.7 Docker images (https://github.com/StackStorm/st2-dockerfiles/blob/v3.7/base/Dockerfile#L1)

The deployment methods like Ansible, Puppet, Docker, or K8s live separated from stackstorm core with their own Changelog.

**Comment by rite2hhh** [comment]
@armab, thanks for the information, this helps!

**Comment by frankpengau** [comment]
@armab Thanks for confirming. I wasn't sure that it made it into the stackstorm v3.7 release as well. This helps a lot.

**Pull request merged**
