### PR TITLE
Official Docker images

### PR DESCRIPTION
**Pull request by armab**
* [x] Build Docker with `ST2_VERSION` dynamic parameter
* [x] Link to official StackStorm Docker Hub
* [x] Add more detailed step-by-step description how to Build and Deploy to Docker Hub

This is used by [CircleCI deployments](https://github.com/StackStorm/st2-packages/blob/master/circle.yml)

### CODE REVIEW

**Comment by dennybaa** [comment]
Would please not make a hurry in merging new stuff. I would like to ask you to work on docker hub side builds... This approach you could keep somewhere in another branch.
It's slow and complicated. 
Unless we confirm that http://docs.docker.com/docker-hub/builds/#remote-build-triggers is not possible to use, we should look in its direction. However you can't just ignore it, but it requires some testing.

**Comment by armab** [comment]
Docker Hub builds won't work. Here are the reasons:

* [x] Can't build many images in parallel, because the limit is 1 max parallel builds for free accounts. Other tasks will be skipped.
* [x] In Docker Hub you can build 1 Dockerfile per repo. It means we need 8 separate repos for each component like `st2api/Dockerfile`
* [x] No parametrized builds, eg. not possible to build tagged images we need (different versions based on different `st2bundle`).
* [x] We need differently tagged `latest`/`1.1.1` for different st2 branches like `master`/`v1.1.1`. That's not possible to do with Docker Hub API/triggers.


I researched this part before.

**Comment by dennybaa** [comment]
Have you tried docker hub?

**Comment by dennybaa** [comment]
Where are the proves of the above?
> 1. Can't build many images in parallel, because the limit is 1 max parallel builds for free accounts. Other tasks will be skipped.

We don't needed it. At all. Enough is only one stackstorm container, others are built via dependencie in 
NO TIME.
> 2.  In Docker Hub you can build 1 Dockerfile per repo. It means we need 8 separate repos for each component like st2api/Dockerfile

Yes this docker way)
> 3. No parametrized builds, eg. not possible to build tagged images we need (different versions based on different st2bundle).

I do not accept without testing. http://docs.docker.com/docker-hub/builds/#remote-build-triggers look at the data passed to the trigger url.

> 4. We need differently tagged latest/1.1.1 for different st2 branches like master/v1.1.1. That's not possible to do with Docker Hub API/triggers.
Same as **3**.

**Comment by armab** [comment]
> look at the data passed to the trigger url.

Here is an example:
- For Docker images created from st2 `master` branch you need `latest` Docker tag.
- For Docker images created from st2 `v1.1.1` branch you need `1.1.1` Docker tag.

It means you first build `st2bundle` for corresponding version and then build child images from that base image.

The question is: How via Docker Hub API to build StackStorm components from `st2bundle:latest` or `st2bundle:1.1.1` dynamically? It's just not possible there, you need to generate Dockerfile "on-fly".

**Comment by dennybaa** [comment]
It's not a big deal to have branches for proper `apt-get install` string to use specific version. Anyway it's cheaper from point of speed and simplicity.

**Comment by armab** [comment]
It's not simplicity during release management for every new release to create +1 branch in each `8` StackStorm repos with Dockerfiles/synchronize them with `st2` branching.

**Comment by dennybaa** [comment]
oh come on) don't be so stubborn)  A simple stackstorm action will happily do it for us!
But we won't loose speed and agility.

**Comment by dennybaa** [comment]
You should understand, that I don't like the current approach because it's **slow**. Can you suggest an alternative?

**Comment by armab** [comment]
I assume Docker thing/push will be moved to StackStorm/staging box (as well as bintray), so probably it's temporary in CircleCI.


probably Staging will have control over deployments based on `end2end` tests. That's what I understood from requerements.

**Comment by dennybaa** [comment]
I totally agree, this might happen a bit later. So what was the idea to
implement this feature...
It was more then enough just make automated built for master, that is
actually what is currently required. Can we do it for just having latest
with master stackstorm branch?

**Comment by armab** [comment]
> Can we do it for just having latest with master stackstorm branch?

We already have that: https://hub.docker.com/r/stackstorm/

----
> It was more then enough just make automated built for master

I don't think so. What's the reason distributing unstable Docker images based only on st2 `master`?
We already **should** deliver working solution, not just MVP.

**Pull request merged**
